services:
  - type: web
    name: smartrack-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: AUTH0_DOMAIN
        value: dev-a5hqcneif6ghl018.us.auth0.com
      - key: AUTH0_AUDIENCE
        value: https://api.smartrack.com
      - key: DEBUG
        value: false












